# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby-lsp-rails` gem.
# Please instead update this file by running `bin/tapioca gem ruby-lsp-rails`.

# source://ruby-lsp-rails//lib/ruby_lsp_rails/version.rb#4
module RubyLsp; end

# # Supported features
#
# - [Hover](rdoc-ref:RubyLsp::Rails::Hover)
# - [CodeLens](rdoc-ref:RubyLsp::Rails::CodeLens)
#
# source://ruby-lsp-rails//lib/ruby_lsp_rails/version.rb#5
module RubyLsp::Rails; end

# source://ruby-lsp-rails//lib/ruby_lsp_rails/railtie.rb#8
class RubyLsp::Rails::Railtie < ::Rails::Railtie; end

# source://ruby-lsp-rails//lib/ruby_lsp_rails/version.rb#6
RubyLsp::Rails::VERSION = T.let(T.unsafe(nil), String)
