// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import NestedForm from "./nested_form_controller";
import { application } from "./application";
import Custom from "./custom_controller";

import HelloController from "./hello_controller";
application.register("hello", HelloController);
application.register("nested-form", NestedForm);
application.register("custom-form", Custom);
